### PR TITLE
Version2

### PR DESCRIPTION
**Pull request by cproensa**
I have rewritten most of it to load a form on demand when opening the dialog
Updates are managed by jquery post() so it doesnt leave the current page
Looking forward to hearing comments, suggestions, etc

### CODE REVIEW

**Comment by dregad** [comment]
We should probably wait for merge of #1 before reviewing this. Also, #4 will probably conflict.

**Comment by cproensa** [comment]
Actually, this is a new implementation of the same concept
My main issue with the original plugin is that it sends the form content into "manage_config_columns_set.php", which has a redirect to "manage_config_columns_page.php". The user ends up in the (ugly) standard page for columns config, away from the initial bug list page.

Its not worth to host as a separate plugin, but different enough to not merge directly.
Would it make sense to make a separate branch, keeping original implementation unaffected?

**Comment by dregad** [comment]
> Would it make sense to make a separate branch, keeping original implementation unaffected?

Possibly yes, but considering I made myself the same remark with regards to the redirection, it probably makes sense that this becomes the next version, as you recommended, in which case maintaining 2 distinct branches would be kind of silly.

I only mentioned #4 because you might want to include this change in your feature branch. Didn't check whether #3 would conflict too.

**Comment by cproensa** [comment]
Damien:
#3 I cant find a reason to not allow configuration for "all projects". User can do it through the standard route "my account -> manage columns". Am i missing something?

#4 is included:
seleccion_073

**Comment by cproensa** [comment]
Maybe this style of form, in a more static version, can be ported to the base "manage_config_columns_page.php"?
The standard form is far from user friendly...

**Comment by dregad** [comment]
> #3 I cant find a reason to not allow configuration for "all projects". User can do it through the standard route "my account -> manage columns". Am i missing something?

No particular reason, that's just how @rombert implemented the original plugin, I have no idea of the rationale, and to be honest did not even test if anything did not work properly for all projects. Maybe he can comment.

**Comment by rombert** [comment]
Apparently I believed in 021f08e09b2d50c12bde5b3897b210f4c872c236 that ALL_PROJECTS is not supported. If this works now I see no reason not to add it.

**Comment by cproensa** [comment]
I believe that was something misread from "manage_columns_inc.php"
there are some comments about ALL_PROJECTS, but that concerns to the situation of the form included from "manage" page, not "account"

> All Projects: only if admin can setup global default columns.
> Specific Project: can set columns for that.  Switch to All Projects to set for all projects.

**Comment by dregad** [comment]
> Maybe this style of form, in a more static version, can be ported to the base "manage_config_columns_page.php"?
> The standard form is far from user friendly...

I fully agree. However, it is probably better to delay this kind of changes to a later time (i.e. MantisBT 2.0 with so-called "modern UI")

**Comment by dregad** [comment]
I just tagged [v1.1 release](https://github.com/mantisbt-plugins/Inline-column-configuration/releases/tag/v1.1), you'll probably want to rebase this on top of it.

**Comment by dregad** [comment]
This has been merged in d458d00194d67cd0c473202a76c441853e2e31fb (for the new AJAX feature) and 73299ce472b7a602f396bf20b4bfcf6dcd99e04c (for MantisBT 2.x compatibility)

**Pull request closed without merging**
